# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='neutral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(default='2222222', max_length=255),
            preserve_default=False,
        ),
    ]
